image: "rustlang/rust:nightly"

before_script:
- apt-get update
- apt-get install -q -y build-essential libssl1.0-dev

script:
- rustc --version && cargo --version
- cargo test --all --verbose

test:latest:
  image: "rust:latest"

test:nightly:
  image: "rustlang/rust:nightly"
