[package]
name = "rs-docker"
description = "Docker Remote API in Rust"
version = "0.0.45"
authors = ["Thiago Areias <kblo.thiago@gmail.com>"]
license = "Apache-2.0"
homepage = "https://gitlab.com/kblobr/rust-docker"
repository = "https://gitlab.com/kblobr/rust-docker.git"
documentation = "https://ghmlee.github.io/rust-docker/doc/docker"
readme = "README.md"
keywords = ["docker"]

[dependencies]
openssl = "0.10.16"
unix_socket = "0.5.0"
rustc-serialize = "0.3.24"
