[package]
name = "rs-docker"
description = "Docker Remote API in Rust"
version = "0.0.51"
authors = ["Thiago Areias <kblo.thiago@gmail.com>"]
license = "Apache-2.0"
homepage = "https://gitlab.com/kblobr/rust-docker"
repository = "https://gitlab.com/kblobr/rust-docker.git"
documentation = "https://ghmlee.github.io/rust-docker/doc/docker"
readme = "README.md"
keywords = ["docker"]

[dependencies]
openssl = { version = "0.10.16", optional = true }
unix_socket = "0.5.0"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.37"

[features]
default = ["openssl"]
